### ISSUE TITLE
CALIDAD Y DIFERENTES TIPOS DE PRUEBA 

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Sandoval6#1]
[INFOGAFRIA_CHARLY.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Sandoval6/files/15461949/INFOGAFRIA_CHARLY.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado. Calificacion 19
